const HEADER_HEIGHT = 56

const CONVERSATION_WINDOW_WIDTH = 328
const CONVERSATION_WINDOW_HEIGHT = 455
const CONVERSATIONS_CONTAINER_MARGIN_RIGHT = 32

const MESSAGE_CONVERSATION_MIN_HEIGHT = 20
const MESSAGE_CONVERSATION_MAX_HEIGHT = 128

export {
  HEADER_HEIGHT,
  CONVERSATION_WINDOW_WIDTH,
  CONVERSATION_WINDOW_HEIGHT,
  CONVERSATIONS_CONTAINER_MARGIN_RIGHT,
  MESSAGE_CONVERSATION_MIN_HEIGHT,
  MESSAGE_CONVERSATION_MAX_HEIGHT,
}